// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ashmtfjgcewegrrgjvio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzaG10ZmpnY2V3ZWdycmdqdmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjQzNTgsImV4cCI6MjA3MzMwMDM1OH0.K9RAHGSTodNhMGuyUjhOwSosjCuk9Rxtfkm2au6sbjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});